export const CITIES = {
  tokyo: {
    slug: "tokyo",
    name: "Tokyo",
    kanji: "東京",
    dates: "Mar 23–31",
    nights: 8,
    lat: 35.6762,
    lng: 139.6503,
    theme: {
      primary: "#0d1b2e",
      accent: "#e91e8c",
      highlight: "#00d4ff",
      surface: "#f0f4ff",
    },
    landmark: "Shibuya Crossing",
    tagline: "34 million people. 1,300 years of temples. Let's start.",
    blossomSpot: "Shinjuku Gyoen",
  },
  nara: {
    slug: "nara",
    name: "Nara",
    kanji: "奈良",
    dates: "Apr 1–2",
    nights: 2,
    lat: 34.6851,
    lng: 135.8048,
    theme: {
      primary: "#2d3a1e",
      accent: "#8b6914",
      highlight: "#c4956a",
      surface: "#f7f3ec",
    },
    landmark: "Todaiji Temple",
    tagline: "1,300 years of sacred ground. The deer were here before the temples.",
    blossomSpot: "Nara Park",
    reminder: "Passport required for Todaiji museum entry.",
  },
  osaka: {
    slug: "osaka",
    name: "Osaka",
    kanji: "大阪",
    dates: "Apr 3–6",
    nights: 4,
    lat: 34.6937,
    lng: 135.5023,
    theme: {
      primary: "#1a0a00",
      accent: "#ff4500",
      highlight: "#f5c518",
      surface: "#fff8f0",
    },
    landmark: "Dotonbori",
    tagline: "Japan's kitchen. They eat out 14 times a week. Keep up.",
    blossomSpot: "Osaka Castle Park",
  },
  kyoto: {
    slug: "kyoto",
    name: "Kyoto",
    kanji: "京都",
    dates: "Apr 6–9",
    nights: 3,
    lat: 35.0116,
    lng: 135.7681,
    theme: {
      primary: "#1a0f0a",
      accent: "#8b1a1a",
      highlight: "#f7b8c4",
      surface: "#faf6f0",
    },
    landmark: "Fushimi Inari",
    tagline: "Ancient capital for 1,000 years. 1,600 temples. Three days is never enough.",
    blossomSpot: "Maruyama Park",
  },
} as const;

export type CitySlug = keyof typeof CITIES;
export type City = (typeof CITIES)[CitySlug];
